version: '3.4'

networks:
  nginx_default:
    external: true
  grafana_default:
    external: true

volumes:
  prometheus:
    name: prometheus

services:
  prometheus:
    image: ${IMAGE}
    networks:
      - default
      - nginx_default
      - grafana_default
    volumes:
      - prometheus:/prometheus
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      placement:
        constraints:
          - node.labels.name == mg1
