version: '3.4'

networks:
  nginx_default:
    external: true
  exim_default:
    external: true

volumes:
  grafana:
    name: grafana

services:
  grafana:
    image: grafana/grafana:9.3.1
    networks:
      - default
      - nginx_default
      - exim_default
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.dmska.ru/
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=exim:25
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      placement:
        constraints:
          - node.labels.name == mg1
