version: '3.4'

volumes:
  mysql:
    name: mysql

services:
  mysql:
    image: ${IMAGE}
    environment:
      - TZ=Europe/Moscow
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      placement:
        constraints:
          - node.labels.name == mg1
