version: '3.4'

services:
  redis-master:
    image: redis:7.0.5-alpine3.17
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      placement:
        constraints:
          - node.labels.name == mg1
