name: Deployment

push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: repo checkout
        uses: actions/checkout@v3

      - name: buildx installation
        uses: docker/setup-buildx-action@v2

      - name: tls secrets to files
        run: |
          echo '${{ secrets.TLS_CA }}' > ca.pem
          echo '${{ secrets.TLS_CERT }}' > cert.pem
          echo '${{ secrets.TLS_KEY }}' > key.pem

      - name: deploy to swarm
        run: |
          docker -H ${{ secrets.HOST_DEV }} \
            --tls \
            --tlscacert ca.pem \
            --tlscert cert.pem \
            --tlskey key.pem \
            stack deploy \
              -c redis/stack.yml redis
